### ISSUE TITLE
Grupo whats Baileys-br

### ISSUE THREAD

**Issue by mateuscdor** [riccefarias/node-red-contrib-kore-whatsappbot#1]
Angelo vi que você utiliza o baileys também
tem um grupo br só de desenvolvedores do baileys
segue o link https://chat.whatsapp.com/Lce2fm3rCyS6K99NtDujAL

**Comment by riccefarias** [comment]
entrei la, vlws 😁

**Comment by costasamuel16** [comment]
Me manda o link tambem para fazer parte

**Comment by mateuscdor** [comment]
https://chat.whatsapp.com/ByYw6AroQ9dAYEsuLXuFDE
