### ISSUE TITLE
Error when QR code is readed - Stream Errored (restart required)

### ISSUE THREAD

**Issue by jrvidotti** [riccefarias/node-red-contrib-kore-whatsappbot#2]
An error is being thrown when QRCode is readed:

`
{"level":50,"time":1656859251261,"pid":18,"hostname":"7ea162767d1b","node":{"tag":"stream:error","attrs":{"code":"515"}},"msg":"stream errored out"}
{"level":30,"time":1656859251263,"pid":18,"hostname":"7ea162767d1b","error":{"data":{"tag":"stream:error","attrs":{"code":"515"}},"isBoom":true,"isServer":true,"output":{"statusCode":515,"payload":{"statusCode":515,"error":"Unknown","message":"Stream Errored (restart required)"},"headers":{}}},"trace":"Error: Stream Errored (restart required)\n    at WebSocket.<anonymous> (/data/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:419:13)\n    at WebSocket.emit (events.js:400:28)\n    at /data/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:219:35\n    at Object.decodeFrame (/data/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:131:17)\n    at WebSocket.onMessageRecieved (/data/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:195:15)\n    at WebSocket.emit (events.js:400:28)\n    at Receiver.receiverOnMessage (/data/node_modules/@adiwajshing/baileys/node_modules/ws/lib/websocket.js:1169:20)\n    at Receiver.emit (events.js:400:28)\n    at Receiver.dataMessage (/data/node_modules/@adiwajshing/baileys/node_modules/ws/lib/receiver.js:513:14)\n    at Receiver.getData (/data/node_modules/@adiwajshing/baileys/node_modules/ws/lib/receiver.js:446:17)","msg":"connection errored"}
{"level":30,"time":1656859251265,"pid":18,"hostname":"7ea162767d1b","error":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":428,"payload":{"statusCode":428,"error":"Precondition Required","message":"Connection Terminated by Server"},"headers":{}}},"trace":"Error: Connection Terminated by Server\n    at WebSocket.<anonymous> (/data/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:351:40)\n    at WebSocket.emit (events.js:400:28)\n    at /data/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:219:35\n    at Object.decodeFrame (/data/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:131:17)\n    at WebSocket.onMessageRecieved (/data/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:195:15)\n    at WebSocket.emit (events.js:400:28)\n    at Receiver.receiverOnMessage (/data/node_modules/@adiwajshing/baileys/node_modules/ws/lib/websocket.js:1169:20)\n    at Receiver.emit (events.js:400:28)\n    at Receiver.dataMessage (/data/node_modules/@adiwajshing/baileys/node_modules/ws/lib/receiver.js:513:14)\n    at Receiver.getData (/data/node_modules/@adiwajshing/baileys/node_modules/ws/lib/receiver.js:446:17)","msg":"connection errored"}
`

I think this might be the cause of error: https://github.com/adiwajshing/Baileys/issues/1823#issuecomment-1168626277

https://github.com/riccefarias/node-red-contrib-kore-whatsappbot/blob/master/whatsapp-client.js#L25

PS: Current dependency `@adiwajshing/baileys-md` links to `@adiwajshing/baileysˆ4.0.0` and current Baileys version is 4.2.0.

**Comment by rubensflinco** [comment]
#3
